### ISSUE TITLE
new discovery boards support

### ISSUE THREAD

**Issue by huegene** [blacksphere/blackmagic#105]
A few new discovery boards feature a highside switch to turn on or off the target µC. Default state is off, this way though the target reset line remains low all the time, preventing regular startup as the blackmagic_dfu assumes dfu boot mode. Since the PwrEn line is pulled up, its possible to detect its presence. 
patch file:
[usbdfu.txt](https://github.com/blacksphere/blackmagic/files/33204/usbdfu.txt)

**Comment by huegene** [comment]
sorry, now a more appropriate patch  
[usbdfu.txt](https://github.com/blacksphere/blackmagic/files/33204/usbdfu.txt)

**Comment by huegene** [comment]
Is there a propper way to add to the code base.  It just seemed like a very minor yet practical patch.

**Comment by gsmcmullin** [comment]
Please create a pull request, and fix to use the Linux kernel coding style.  Then I will merge it.

**Comment by gsmcmullin** [comment]
Applied in 0480578
