### ISSUE TITLE
Add .editorconfig file to github please

### ISSUE THREAD

**Issue by fordp2002** [blacksphere/blackmagic#109]
I can see you are using Tabs in your code (I like this). Git hub stupidly shows the files on the website with a tab size of 8 which is not cool.

You can fix this by adding a .editorconfig file to the root of the project.

Feel free to use a hacked version of my file from here: https://github.com/fordp2002/ArmCopro.

This is an awesome project. Intend to contribute to it in the coming months!

I am not sure if your adapter can work with a raspberry Pi (to debug the Pi I mean).

FordP

**Comment by gsmcmullin** [comment]
I don't consider this broken.  The project uses Linux kernel coding style, and lines are kept short even with tabs displayed as 8 chars.

Support has recently been added for some ARMv7-A Cortex-A devices, including Raspberry Pi 2.  Unfortunately the original Raspberry Pi, and the new version 3 are not currently supported.
