### ISSUE TITLE
Default max number of JTAG devices is too small

### ISSUE THREAD

**Issue by adamgreig** [blacksphere/blackmagic#112]
At the moment [`JTAG_MAX_DEVS`](https://github.com/blacksphere/blackmagic/blob/master/src/include/jtag_scan.h#L24) is 5, but since each STM32 IC (and I assume others) presents as a debug port and the CPU core separately, this in practice means the limit is 2 ICs on a daisychain, and `JTAG_MAX_DEVS` might as well be set to 4 instead of 5.

Since increasing this just uses 14 bytes of RAM or so per device, is there any reason not to increase it to say 32? I'm currently using a build with this set to 32 on a chain of 3 STM32s without issue (but had to increase it from 5 to get the scan to succeed with 3 ICs on the chain). I appreciate that daisychaining lots of microcontrollers on JTAG is uncommon but since it is supported, might as well support it with more than just two chips?

**Comment by gsmcmullin** [comment]
Thanks for the feedback, Adam.  The number 5 was quite arbitrary.  I'll increase this to 32 and push.
