### ISSUE TITLE
GNU ARM 4.7.4 20130913 crash to build the firmware (requires GCC ARM 4.9.3)

### ISSUE THREAD

**Issue by bvernoux** [blacksphere/blackmagic#128]
## Test1 KO GNU ARM Embedded  4.7.4 20130913
Tested on Windows 7 SP1 64bits (with 16GB RAM + SSD)
GNU_ARM_4_7_2013q3\bin\arm-none-eabi-gcc.exe --version
arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors) 4.7.4 20130913 (re
lease) [ARM/embedded-4_7-branch revision 202601]

```
make
...
CC      main.c
cc1.exe: out of memory allocating 65536 bytes
make[1]: *** [main.o] Error 1
make: *** [all] Error 2
```

## Test2 OK ARM Embedded  4.9.3 20141119
Tested on Windows 7 SP1 64bits (with 16GB RAM + SSD)
GNU_ARM_4_9_2014q4\bin\arm-none-eabi-gcc.exe --version
arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors) 4.9.3 20141119 (re
lease) [ARM/embedded-4_9-branch revision 218278]
```
make
...
LD      blackmagic_dfu
OBJCOPY blackmagic_dfu.bin
OBJCOPY blackmagic_dfu.hex
```

## Test3 OK ARM Embedded 4.9.3 20150529
Tested on Windows 7 SP1 64bits (with 16GB RAM + SSD)
GNU_ARM_4_9_2015q3\bin\arm-none-eabi-gcc.exe --version
arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors) 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977]

```
make
...
LD      blackmagic_dfu
OBJCOPY blackmagic_dfu.bin
OBJCOPY blackmagic_dfu.hex
```

## Test4 OK ARM Embedded 5.3.1 20160307
Tested on Windows 7 SP1 64bits (with 16GB RAM + SSD)
GNU_ARM_5_3_2016q1\bin\arm-none-eabi-gcc.exe --version
arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors) 5.3.1 20160307 (re
lease) [ARM/embedded-5-branch revision 234589]

```
make
...
LD      blackmagic_dfu
OBJCOPY blackmagic_dfu.bin
OBJCOPY blackmagic_dfu.hex
```

**Comment by bvernoux** [comment]
Note I have not tested on GNU_ARM_4_8_2014q3, GNU_ARM_4_9_2014q4, GNU_ARM_4_9_2015q2 ... so it probably works on those version
It is just a big warning for anyone using GNU ARM 4.7.4 20130913

**Comment by gsmcmullin** [comment]
This is not a bug in the blackmagic firmware.
