### ISSUE TITLE
Flashing program over SWD

### ISSUE THREAD

**Issue by tejainece** [blacksphere/blackmagic#150]
How is a new program flashed over SWD ADI interface? Is an IAP program loaded into RAM and then is it used to write flash memory?

I am wondering how to add new boards/chips to the already supported list. or is it supported out of the box through ADI interface?

Thanks!

**Comment by gsmcmullin** [comment]
The ADIv5 interface does not directly provide a way to write to flash.  It's implemented differently for different target devices.

There are a few basic patterns for how this is done:
- 'Direct' - writes are passed directly to the target driver which programs the flash directly using MMIO. (eg. `kinetis.c`)
- 'Buffered' - the target layer will buffer write packets from GDB until and pass to the driver as writes of whole sectors.  The driver will program the target flash directly using MMIO. This works well when whole sectors can be programmed with sequencial writes. (eg. `stm32l0.c`)
- 'Stubbed' - writes are passed directly to the target driver which writes a program stub and the data payload to the target.  The stub is then executed to program the device. This works well when flash can't be programmed with sequential writes. (eg. `stm32f1.c`)
- 'LPC' - NXP devices include a built in ROM for programming flash.  There is no published MMIO mechanism to program the flash on these devices. (eg. `lpc11xx.c`)
