### ISSUE TITLE
EFM32HP (happy gecko) support

### ISSUE THREAD

**Issue by linuxchris12** [blacksphere/blackmagic#169]
The Happy Gecko is not in the targets file yet. Needs a

`#define EFM32_DI_PART_FAMILY_HAPPY_GECKO	77`

and

`		case EFM32_DI_PART_FAMILY_HAPPY_GECKO:
			sprintf(variant_string,
				"EFM32 Happy Gecko);
			flash_page_size = 1024;
			break;`

in efm32.c

**Comment by gsmcmullin** [comment]
Applied the changes in #170.
