### ISSUE TITLE
Paypal button on readme gives error

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [blacksphere/blackmagic#176]
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=N84QYNAM2JJQG

> Error Detected
>Error Message
>
>Some required information is missing or incomplete. Please correct your entries and try again.

**Comment by gsmcmullin** [comment]
The link works for me, I get this (tested in Chromium on Linux):
![image](https://cloud.githubusercontent.com/assets/466364/20898647/05e460d0-bb8c-11e6-9619-92d5d5777d0b.png)

**Comment by rogerclarkmelbourne** [comment]
Umm
Seems to be working fine this morning, but @rickkimball told me he also got an error; though I think it may have been when using a tablet computer .

I'll close this now and re-open if it re-occurs
