### ISSUE TITLE
Legacy ARM target support

### ISSUE THREAD

**Issue by gsmcmullin** [blacksphere/blackmagic#178]
This is not actively been worked on. This issue is just a placeholder for reference to relevant documentation and/or other references.

**Comment by gsmcmullin** [comment]
Incomplete ARM7TDMI driver removed from current firmare:
https://github.com/blacksphere/blackmagic/blob/ee3af96a736139b71678a0e590865f9ffafc2f35/src/arm7tdmi.c

For ARM11 (Raspberry Pi 1) support see chapters 13 and 14 from:
http://infocenter.arm.com/help/topic/com.arm.doc.ddi0301h/DDI0301H_arm1176jzfs_r0p7_trm.pdf

**Comment by esden** [comment]
As this is marked as Won't fix I am closing this issue. In case someone decides to work on adding support for old ARM targets this still can be referred to.
