### ISSUE TITLE
gdb 7.12 fails with remote packet timeouts

### ISSUE THREAD

**Issue by alex31** [blacksphere/blackmagic#181]
Hello,

I meet a problem with arm-none-eabi-gdb. With gdb 7.10 (which come with gcc5.x), all is fine, but
with gdb 7.12  (which come with gcc6.x), load fail only if .bin is more than 128ko / 128kb (target is an stm32f4)

trace with gdb 7.10 (when it works) :
`No. Att Driver
 1      STM32F4xx
Loading section .vectors, size 0x1c0 lma 0x8000000
Loading section .text, size 0x2061c lma 0x80001c0
Loading section .rodata, size 0x3ab0 lma 0x80207dc
Loading section .ARM.exidx, size 0x8 lma 0x802428c
Loading section .data, size 0xbf4 lma 0x8024294
Loading section .ram0_init, size 0x4fc lma 0x8024e88
Start address 0x80001c0, load size 152452
Transfer rate: 14 KB/sec, 929 bytes/write.
`

trace with gdb 7.12 (when it fails) :
`Available Targets:
No. Att Driver
 1      STM32F4xx
Ignoring packet error, continuing...
Loading section .vectors, size 0x1c0 lma 0x8000000
Error writing data to flash
`

I use black magic probe up2date from git repo.

Alexandre

**Comment by philcrump** [comment]
I'm also seeing this.

> $ arm-none-eabi-gdb --version
> GNU gdb (GNU Tools for ARM Embedded Processors) 7.12.0.20161204-git

Target: STM32F429ZI (Ethernet Nucleo)

**Comment by UweBonnes** [comment]
With 7.12 erasing larger chunks also times out for me

**Comment by gsmcmullin** [comment]
The problem appears to have been introduced in GDB, in commit 048094acc.

Function `wait_for` in `ser-unix.c` is probably the source of the issue.  It was rewritten to timeout using `select` instead of setting `VTIME`/`VMIN`.

**Comment by UweBonnes** [comment]
How to proceed? And why does does gdb not honor setting a larger timeout?

**Comment by gsmcmullin** [comment]
GDB bug report: https://sourceware.org/bugzilla/show_bug.cgi?id=21188

I'll try send in a patch for GDB.  Even if it's accepted, it'll take a long time before it finds its way downstream to gcc-arm-embedded.

**Comment by esden** [comment]
The patch for this has been merged upstream: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=9bcbdca808b5f9fec6217d20bd4b48a56008c460 I assume this will become available with the 8.0 release that is being prepared at the moment.

**Comment by gsmcmullin** [comment]
GDB 8.0 has been released, which includes this fix.

**Comment by UweBonnes** [comment]
The reference to this issue in #89 was not meant to reopen #181!
