### ISSUE TITLE
JTAG Connector manufacturer product numbers

### ISSUE THREAD

**Issue by zhivko** [blacksphere/blackmagic#186]
I have difficulties to find product numbers of jtag connectors probe side and target board side.
Is it possible to add those information?

**Comment by gsmcmullin** [comment]
https://github.com/blacksphere/blackmagic/wiki/Frequently-Asked-Questions#what-are-those-connectors

**Comment by esden** [comment]
Added some more information and links to the wiki. 
* JTAG/SWD connectors and cables: https://github.com/blacksphere/blackmagic/wiki/Frequently-Asked-Questions#what-are-those-jtagswd-connectors-and-cables
* UART connectors and cables:  https://github.com/blacksphere/blackmagic/wiki/Frequently-Asked-Questions#what-are-those-uart-connectors-and-cables
