### ISSUE TITLE
Add STM32F41[2|3]

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#197]
Appended patch adds STM32F41[2|3]. Tested with nucleo-f413zh.
[Uploading 0001-Handle-STM32F41-2-3.patch.txt…]()

**Comment by esden** [comment]
Thank you for the patch, but can you make this a normal github pull request? The way you uploaded the patch does not work. (the link leads back to this issue instead of a patch)

**Comment by esden** [comment]
I am closing this issue because you submitted the patch via the mailinglist. Thank you. :)
