### ISSUE TITLE
Signed drivers for Windows?

### ISSUE THREAD

**Issue by edogaldo** [blacksphere/blackmagic#200]
Dears is there any chance to have signed drivers for windows?

Thanks in advance and best regards, E.

**Comment by gsmcmullin** [comment]
#157 claims to provide a signed driver, but it didn't work for me.  See this discussion there.

**Comment by esden** [comment]
As far as I understand the zadig drivers take care of this issue. If new signed drivers are needed please feel free to open this issue again or open a new one with up to date requirements.
