### ISSUE TITLE
v1.6 release testing

### ISSUE THREAD

**Issue by gsmcmullin** [blacksphere/blackmagic#211]
Tests:
- Scan and attach
- Load program to flash
- Verify flash programming
- Start (Temporary flash breakpoint and execution control)
- Memory inspection

Target hardware:
- [x] 1Bitsy (STM32F4)
- [x] Lisa/M v1 (STM32F1)
- [x] EK-TM4C123GXL (TM4C)
- [x] FRDM-KL03Z (KL03Z)
- [x] FRDM-K22F
- [x] Arduino Due (SAM3X)
- [x] SparkFun nRF52 (nRF52832)
- [x] LPCXpresso4337 (LPC43S37)
- [x] LPCXpresso812 (LPC812)

**Comment by esden** [comment]
The list of targets that I have tested successfully:

Each test includes:
* Scan
* Attach
* Load
* Verify flash
* Run
* Interrupt
* Memory inspection

Hardware:
- [x] 1Bitsy (STM32F4)
- [x] Lisa/M V1 (STM32F1)
- [ ] EK-TM4C123GXL (TM4C)
- [x] FRDM-KL03Z (KL03Z)
- [ ] FRDM-KL22F (KL22F)
- [x] Adafruit Bluefruit LE (nrf51822)
- [ ] SparkFun nRF52832 Breakout (nRF52832)

**Comment by esden** [comment]
Based on the information above I think we have good confidence that we can release the 1.6 stable version.
