### ISSUE TITLE
stm32_mem.py does not work

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#253]
Running stm32_mem on a BMP modified ST-Link V2-1 hanged when writing at 0x80005000. Attaching with gdb and comparing the bootloader showed that the bootloader was overwritten!

Pull request #252 makes things work for me.

Did stm32_mem.py work for anybody before?

**Comment by UweBonnes** [comment]
stm32_mem.py also writes above 64 kiB on a F103C8 on a ST-Link older than V2-1

**Comment by gsmcmullin** [comment]
Fixed by #252.  Reopen if the problem persists.
