### ISSUE TITLE
stm32_mem.py should not hardcode start of writable flash

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#254]
stm32_mem.py should evaluate the usb descriptor string describing the internal flash and not use hardcoded values.

**Comment by UweBonnes** [comment]
As evaluating the string is some effort, and also acting correct on the different page sizes e.g. on a F4, perhaps stm32_mem should perhaps only work on a BMP device.

**Comment by gsmcmullin** [comment]
Fixed in #284
