### ISSUE TITLE
efm32 driver sets msc registers without first setting EFM32_MSC_LOCK_LOCKKEY

### ISSUE THREAD

**Issue by dholth** [blacksphere/blackmagic#266]
For example, in efm32_flash_erase, `target_mem_write32(t, EFM32_MSC_WRITECTRL, 1);` is set without first setting `target_mem_write32(t, EFM32_MSC_LOCK, EFM32_MSC_LOCK_LOCKKEY);`.

After the first flash write the stub will leave the MSC unlocked. Could this bug be causing initial flakiness in the driver or is there another mitigating factor that makes it okay?

**Comment by kanflo** [comment]
This was fixed in `98faaceb`, perhaps this issue can be closed?

**Comment by UweBonnes** [comment]
Closing as requested by kanflo. Thanks!
