### ISSUE TITLE
Support for MSP430

### ISSUE THREAD

**Issue by KarolTx** [blacksphere/blackmagic#269]
Hi all,
is it possible to flash the MSP430? JTAG or SBW? How much hacking would it require to get it running?
Cheers,
Karol

**Comment by gsmcmullin** [comment]
There is no support for MSP430 at the moment, and it would probably take quite a bit of effort to implement.  As far as I know there isn't anyone working on this.

This wiki page should have some documentation but hasn't really been written yet:
https://github.com/blacksphere/blackmagic/wiki/Adding-target-drivers

You'd need to implement most of the methods here:
https://github.com/blacksphere/blackmagic/blob/master/src/target/target_internal.h#L79-L129
Methods for break-/watchpoints are optional.
