### ISSUE TITLE
JTAG support on ST-Link V2

### ISSUE THREAD

**Issue by hackrid** [blacksphere/blackmagic#278]
Hi,

I am looking for a debug adapter to debug an esp32 which requires JTAG.
On aliexpress I found this adapter: https://es.aliexpress.com/item/ST-Link-st-link-V2-for-STM8S-STM8L-STM32-Cortex-M0-Cortex-M3-SWIM-JTAG-SWD/32322884886.html

can BMP work with this ?

**Comment by UweBonnes** [comment]
Neither BMP nor stock OpenOCD support ESP32. It seems, there are add-ons to openOCD to support ESP32. Above adapter should probably work with OpenOCD.
