### ISSUE TITLE
USB string errors with 64 byte strings

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#282]
Hello,

libusb pull request #824 cares for the terminating 0 in usb strings.

For stlink some exact 64 byte product string was generated. As no terminating 0 was in the UTF string, the string request went wild. stm32_mem.py crashed. ACM terminals took about 5 seconds after enumerations to appear.

Pleas apply to the bmp libopencm3 fork.

**Comment by gsmcmullin** [comment]
Update libopencm3 submodule to include commit 3ed12b6fd944c4b3c921b8f73a6912f856edb68a for zero-length packet fix for control transfers.

**Comment by gsmcmullin** [comment]
Fixed by PR #287
