### ISSUE TITLE
Release binaries for the bluepill

### ISSUE THREAD

**Issue by zoobab** [blacksphere/blackmagic#309]
Hi,

Would it be possible to also release binaries for the bluepill?

Best,

**Comment by UweBonnes** [comment]
Try the binaries at https://github.com/UweBonnes/blackmagic/tree/bluepill on your own risk.

**Comment by probonopd** [comment]
I can't seem to find binaries there @UweBonnes

**Comment by UweBonnes** [comment]
Why can't you compile yourself?

**Comment by probonopd** [comment]
Thanks @UweBonnes that's what I have done now, but running into an [issue](https://github.com/sandeepmistry/arduino-nRF5/issues/252) which I am not sure whether it is caused by the BMP firmware.
