### ISSUE TITLE
NRF5 stuck in reset until scan is started

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#320]
Hello,

in https://github.com/sandeepmistry/arduino-nRF5/issues/252some user reports that the NRF5 does not start until a scan command is issued. As described there, SDWIO and Reset share the same line. Startup code of  the different platforms sets SWDIO low when BMP initializes the board, obvious causing this issue.

https://github.com/UweBonnes/blackmagic/tree/pin-defaults cares for the right  SDWIO and TDI defaults. 

Awaiting user reports...

**Comment by probonopd** [comment]
Just a heads-up, I am currently away from the devices with no way to test. Will follow your suggestions and give an update, most likely next week. Thanks for your help.

**Comment by probonopd** [comment]
Thanks @UweBonnes but after power cycling, SDWIO soldered to PB14 still is low.

**Comment by rpavlik** [comment]
FYI, I have an adafruit nRF52 feather and will presumably be using the BMP v2.1 on it shortly.

**Comment by flatsiedatsie** [comment]
This sounds like this problem:

https://forum.mysensors.org/topic/6961/nrf5-bluetooth-action/1583

> nrf52.cpu curstate
reset

**Comment by UweBonnes** [comment]
Well, BMP should keep SWDIO tristated until needed. While tristated, pull-up internal to target SWDIO and maybe external will do the right thing.

**Comment by UweBonnes** [comment]
Goggle slogans you don't understand first. Than ask more exact.

**Comment by UweBonnes** [comment]
People with this problem please try #361. This pull request keeps TMS tristated until th scan happens. Please report!

**Comment by joric** [comment]
Related problem. I use the following script to flash new firmware:

`arm-none-eabi-gdb.exe --quiet --batch -ex "target extended-remote \\.\%port%" -ex "mon swdp_scan" -ex "file %file:\=/%" -ex "att 1" %opt% -ex "load" -ex "run"`

Ctrl+C works fine (console closes, MCU keeps running), but -ex "quit" or -ex "reset" somehow hangs the MCU. How to fix? I want a script that flashes fimware and restarts MCU on exit.

**Comment by UweBonnes** [comment]
Maybe "-ex run -ex detach" is executed to fast and detach happens while CPU is still in reset. Has gdb some mean of delay?

**Comment by joric** [comment]
I can't use -ex run in a batch file because it's not interactive. It's just -ex load -ex kill. Don't know about delay.
