### ISSUE TITLE
STM32L496 support

### ISSUE THREAD

**Issue by arthurv** [blacksphere/blackmagic#323]
Hi,

I've been able to connect to an STM32L476 target and start debugging, however I cannot connect to a close relative chip STM32L496. Is it possible to add support for the L496?
```
(gdb) monitor swdp_scan
Target voltage: unknown
Available Targets:
No. Att Driver
 1      STM32L4xx
(gdb) attach 1
Attaching to Remote target
Attaching to Remote target failed
```

**Comment by UweBonnes** [comment]
Please try #310

**Comment by arthurv** [comment]
@UweBonnes tried it, unfortunately I still get the same issue. Unplugging from my L496 target and plugging in to my L476 target confirms it's still not compatible with L496. Targets are electrically identical except for the uC.

**Comment by UweBonnes** [comment]
Does the L49 hardware really work as expected? Can you connect to the L49 with some other debugger?

**Comment by arthurv** [comment]
Apologies - it was the code running on the L496 which was preventing GDB from attaching to the target. I can confirm it works now.
