### ISSUE TITLE
Intrusive behaviour of BMP

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#328]
Hello,
if I understand "mon j|s" and "att x" right, there is always a system reset issued, either by SRST/nRST if CORTEXM_TOPT_INHIBIT_SRST is not set for the target and always by CORTEXM_AIRCR_SYSRESETREQ during attach. There are situation where a target has crashed with the debugger not yet attached. To debug this situation it would be helpfull if attach to the target would be possible without reset clearing the backtrace of the crash.

**Comment by gsmcmullin** [comment]
Where do you see code that resets the target during attach?  I've attached to running targets often with no problems.

**Comment by UweBonnes** [comment]
Sorry, I was on the wrong track. Closing!
