### ISSUE TITLE
performance difference in using various microcontrollers

### ISSUE THREAD

**Issue by rgujju** [blacksphere/blackmagic#346]
Hello, I am trying to make my own BMP. and deciding which microcontroller to use.
I was wondering what would be the performance differences if i were to use say STM32F3 which has USB vs something like LPC11XX which does not have USB as the BMP.

The BMP firmware does support both of these micros.

**Comment by UweBonnes** [comment]
BMP supports the LPC11, but BMP itself is not ported to LPC11.
If you use some other platform than those in src/platforms/, you neded to write the platform support yourself.

**Comment by rgujju** [comment]
oh ok. thank you.
