### ISSUE TITLE
Support for Kinetis KE04Z8 

### ISSUE THREAD

**Issue by newbrain** [blacksphere/blackmagic#352]
I will shortly receive some MKE04Z8VTG4.
Since I have no probes that works out of the box with them, I'm going to add the support in blackmagic.

The current kinetis target is an excellent base, but some flash register and the actual probing are slightly different (e.g.: no SIM_SDID register).

When/if I submit a pull request with the support is it advised to modify the existing kinetis.c or create a specific ke04 target file (so with separate probing)?
The former  avoids redundant code (most of the flashing routines are going to be very similar), the latter makes for cleaner code, to the expense of compiled size.

I can probably add support for MKE04Z64/128 too, but I will not be able to test it.
What is the policy for inserting experimental features (e.g. protecting with \#ifdef)?

Thanks for your insights.

**Comment by UweBonnes** [comment]
Redundant vs cleaner code  has no yes/no answer. Already present code can be a guidance, but may not be perfect too.
 Ifdef proteced experimental feature should not go into pull request. If you look at the present ifdef usage, it is mostly for extra debug output.

B.t.w, for fast code//debug cycles, consider a (SWD capable ?) FTDI dongle. It saves you from downloading changed firmware to the dongle and allows direct debug output to the console. Git head contains changes that make FTDI SWD usable i.m.h.o. Feedback welcome.

**Comment by newbrain** [comment]
Thanks, your feedback is appreciated!
Good suggestion, I might get an FTDI adapter.
I'll initially go for cleaner code, and check the binary size increase.
