### ISSUE TITLE
make PROBE_HOST=stlink  failes with error

### ISSUE THREAD

**Issue by pfodApp** [blacksphere/blackmagic#355]
Downloaded code as zip file and unzip and ran make PROBE_HOST=stlink 
...
  AR      libopencm3_vf6xx.a
  GIT     include/version.h
fatal: Not a git repository (or any of the parent directories): .git
...

platforms/common/cdcacm.c: In function 'cdcacm_set_config':
platforms/common/cdcacm.c:534:4: error: passing argument 4 of 'usbd_register_con
trol_callback' from incompatible pointer type [-Werror=incompatible-pointer-type
s]
    cdcacm_control_request);
    ^~~~~~~~~~~~~~~~~~~~~~
In file included from platforms/stlink/platform.h:34:0,
                 from include/general.h:33,
                 from platforms/common/cdcacm.c:29:
../libopencm3/include/libopencm3/usb/usbd.h:136:12: note: expected 'usbd_control
_callback {aka enum usbd_request_return_codes (*)(struct _usbd_device *, struct
usb_setup_data *, unsigned char **, short unsigned int *, void (**)(struct _usbd
_device *, struct usb_setup_data *))}' but argument is of type 'int (*)(usbd_dev
ice *, struct usb_setup_data *, uint8_t **, uint16_t *, void (**)(usbd_device *,
 struct usb_setup_data *)) {aka int (*)(struct _usbd_device *, struct usb_setup_
data *, unsigned char **, short unsigned int *, void (**)(struct _usbd_device *,
 struct usb_setup_data *))}'
 extern int usbd_register_control_callback(usbd_device *usbd_dev, uint8_t type,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make[1]: *** [cdcacm.o] Error 1
make: *** [all] Error 2

**Comment by UweBonnes** [comment]
Where did you download the zip file?
BMP is distributed via git from github. Other sources are out of our control!

**Comment by pfodApp** [comment]
went back and checked out using GIT instead of using zip files
i.e. git clone https://github.com/blacksphere/blackmagic.git
cd /path/to/blackmagic
git submodule init
git submodule update

Then make PROBE_HOST=stlink give this error

In file included from ../../../include/libopencm3/cm3/nvic.h:133:0,
                 from ../../../include/libopencm3/cm3/vector.h:41,
                 from ../../cm3/vector.c:22:
../../../include/libopencm3/dispatch/nvic.h:6:11: fatal error: libopencm3/stm32/
f0/nvic.h: No such file or directory
 # include <libopencm3/stm32/f0/nvic.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [vector.o] Error 1
make[1]: *** [lib/stm32/f0] Error 2
make: *** [all] Error 2

**Comment by UweBonnes** [comment]
Okay, you are working on windows. Will check and come back...

**Comment by pfodApp** [comment]
Third attempt using cygwin and http://www.sidprice.com/2018/05/23/cortex-m-debugging-probe/ instructions
make clean
make PROBE_HOST=stlink
give this error

c:\Program Files (x86)\GNU Tools ARM Embedded\7 2017-q4-major\bin\arm-none-eabi-ar.exe: c:/cygwin64/home/matthew/blackmagic/libopencm3/lib/libopencm3_lpc17xx.a: Permission denied
make[2]: *** [/c/cygwin64/home/matthew/blackmagic/libopencm3/lib/libopencm3_lpc17xx.a] Error 1
make[1]: *** [lib/lpc17xx] Error 2
make: *** [all] Error 2

**Comment by UweBonnes** [comment]
Did you closely follow http://www.sidprice.com/2018/05/23/cortex-m-debugging-probe/

**Comment by pfodApp** [comment]
using chmod 777 on lib/* seemed to fix this error

**Comment by pfodApp** [comment]
Started from https://github.com/electronut/ElectronutLabs-bluey/blob/master/blackmagic-prog.md
and ended up at http://www.sidprice.com/2018/05/23/cortex-m-debugging-probe/
by that time I had installed https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
I did not do the mount ..   as I ran git from within cygwin.
the 
cd src
make
did not work at all
ElectronutLabs  seemed to imply that all that was needed was 
make PROBE_HOST=stlink
Finally got a full compile by 
make clean
make PROBE_HOST=stlink
cd libopencm3
chmod 777 lib/*
cd ..
make PROBE_HOST=stlink
cd libopencm3
chmod 777 lib/*
cd ..
make PROBE_HOST=stlink
....
....
  OBJCOPY blackmagic.bin
  CC      platforms/stlink/usbdfu.c
  CC      platforms/stm32/dfucore.c
  CC      platforms/stm32/dfu_f1.c
  LD      blackmagic_dfu
  OBJCOPY blackmagic_dfu.bin
  OBJCOPY blackmagic_dfu.hex
  CC      platforms/stlink/dfu_upgrade.c
  LD      dfu_upgrade
  OBJCOPY dfu_upgrade.bin
  OBJCOPY dfu_upgrade.hex


each call to make seemed to get a bit further.  But something is wrong with the permission settings in the script.
Have not tested the final files yet  Awaiting the hardware.

**Comment by lorenz** [comment]
The toolchain on Ubuntu 18.04 is indeed a problem. A firmware built from the same source in a Fedora container works, but the same build on Ubuntu 18.04 HardFaults pretty much immediately. Both builds are over 64K, so no difference in the handling of high flash.

**Comment by pfodApp** [comment]
Hardware arrived and loaded the .bin files obtained above.
Could not get Windows drivers to recognize the board.
Tried using zadig-2.3.exe but while it found the board and loaded drivers still did not get two valid com ports.
So for now  I  putting this aside and am looking at other replacements for Redbear Nano V1.5 programming board for nrf52xx chips
