### ISSUE TITLE
Support for ERASEALL command on nrf52 when 'Access port protection' is enabled

### ISSUE THREAD

**Issue by ntavish** [blacksphere/blackmagic#380]
I've tested this only on nRF52840 dongle at the moment, but `nrf51_cmd_erase_all` does not seem to be actually erasing the flash and UICR areas with the bootloader that came with the pca100059 dongle. The `nrf51_cmd_erase_all()` method (for `mon erase_mass`) does not seem to be doing [this](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.whitepapers%2Fdita%2Fwhitepapers%2Fnwp_027%2FnWP_027_approtect.html).

Any ideas on how to add this functionality? 'SWD ARM® CoreSight™ DAP' would probably not be in `nrf51.c` but I don't know enough about this to know how this would work.

Thanks

**Comment by miek** [comment]
Support for this was recently merged (in #378). You'll need to build and flash BMP firmware from git master and then when you scan you should see a second port to attach to. Attach to that and run `erase_mass`.

**Comment by ntavish** [comment]
Thanks, seems to have worked, closing.

**Comment by jtam007** [comment]
I seem to be having some trouble with this. Loaded GDB, attached to the second port for nRF52. 
Run: 'mon erase_mass'

Results is a bunch of timeouts:
Nordic nRF52 Access Port specific commands:
Packet received: O0965726173655f6d617373202d2d20457261736520656e7469726520666c617368206d656d6f72790a
	erase_mass -- Erase entire flash memory
Packet received: OK
(gdb) mon erase_mass
Sending packet: $qRcmd,65726173655f6d617373#a3...Ack
Timed out.
Timed out.
Timed out.
Ignoring packet error, continuing...
Timed out.
Timed out.
Timed out.
Ignoring packet error, continuing...
Timed out.
T

If I try to read the CTRL-AP ID register 'x/1xw 0x0FC', It says '0xfc:	Cannot access memory at address 0xfc'

I cannot manually start the Erase All process by writing to ERASEALL either or issue a reset through the CTRL port.
