### ISSUE TITLE
Bad types

### ISSUE THREAD

**Issue by jacereda** [blacksphere/blackmagic#400]
https://github.com/blacksphere/blackmagic/blob/b2defad844466bee4024d786f9c4a7ef6ed6fffe/src/platforms/libftdi/swdptap.c#L189
https://github.com/blacksphere/blackmagic/blob/b2defad844466bee4024d786f9c4a7ef6ed6fffe/src/platforms/libftdi/swdptap.c#L212

s/uint /unsigned /g

**Comment by UweBonnes** [comment]
sys/types.h:typedef unsigned int uint;

Where is the problem?

Please close!

**Comment by jacereda** [comment]
That might be on Linux. Darwin doesn't define it.

**Comment by UweBonnes** [comment]
Okay. I will put the fix in my ftdi branch.

**Comment by UweBonnes** [comment]
But it always helps to be mpre verbose.

**Comment by UweBonnes** [comment]
Fixed with #427
