### ISSUE TITLE
Impossible to use BMP, SW-DP scan failed

### ISSUE THREAD

**Issue by benjaminpeere** [blacksphere/blackmagic#404]
Hello,
I am having trouble into using Black magic probe with my stm32f103c8.
First of all I tried this tutorial : https://medium.com/@paramaggarwal/converting-an-stm32f103-board-to-a-black-magic-probe-c013cf2cc38c
to create my own black magic probe, but it didn't work.
I found some binaries files in this git : https://github.com/rogerclarkmelbourne/blackmagic_archive_version/tree/master/binaries
I have succeed to upload one in my stm32 this way : 
![image](https://user-images.githubusercontent.com/19531148/47502615-8e46c080-d868-11e8-8dad-a3be3b0ab4fa.png)
and it seems to work, I can use gdb, until I make this command : monitor swdp_scan
![image](https://user-images.githubusercontent.com/19531148/47502687-bc2c0500-d868-11e8-85f7-6b44a0f393b7.png)
It's been 2 days now that I am on this error, I absolutely Don't understand what I am doing wrong.
If you have any idea you would help me a lot!
Thank you!

**Comment by UweBonnes** [comment]
Why can you use GIT head? Read the README.md in src/platforms/swlink and compile for swlink.

**Comment by benjaminpeere** [comment]
How do I compile for swlink?

**Comment by esden** [comment]
Closing this issue as it is stale.
