### ISSUE TITLE
add info about blue pill dev board to the documentation

### ISSUE THREAD

**Issue by mczerski** [blacksphere/blackmagic#411]
It seems that the swlink platform supports also the "blue pill" dev board. Maybe it should be added to the documentation on the wiki page in the "Debugger Hardware" section. It would save me the whole eavning trying to modify the stlink platform to use PA13/14 pins for the swd connection :)

**Comment by UweBonnes** [comment]
Done. Please review https://github.com/blacksphere/blackmagic/wiki/Debugger-Hardware/
