### ISSUE TITLE
Is it possible to upload FW to BMP v2.1 using USB connection or another BMP 2.1?

### ISSUE THREAD

**Issue by navado** [blacksphere/blackmagic#418]
What is the required wiring of the probe(s) to upload FW to BMP 2.1 (by [1BitSquared](https://1bitsquared.com/collections/all-products/products/black-magic-probe))

To try using some fixes from pull requests.

**Comment by UweBonnes** [comment]
I assume you succeeded in compiling the firmware. First try "../scripts/stm32mem <firmware.bin>" with an USB connection. . You can also load the firmware with a SWD or JTAG connection, however this requires additional wiring.

**Comment by navado** [comment]
Thank you.
Finally I figured out how to use upgrade tool and added some documentation in Hacking page.
