### ISSUE TITLE
[RFC] Different approach in defining the target-specific data and functions

### ISSUE THREAD

**Issue by errordeveloper** [blacksphere/blackmagic#42]
I really like how Black Magic Probe makes it so simple to hook-up GDB.

So I had a brief look at implementation and one thing I figured that basically if one will keep adding support for more and more targets, it will increment code size and require larger MCU...

So I have started thinking, what if a target functions and data where to be defined in some sort of a config file or script (may be JSON or Lua) and all the firmware need to have is the parser for that, so it wouldn't grow and the config or script files can reside on an SD card, perhaps.
If someone wanted to put the BMP on the same board as the target, they could potentially pre-parse their config (or script) and make it part of the firmware that way (in the case of Lua there exists a Lua to C compiler, for example).

It would also simplify the implementation for each new target, I suppose.

**Comment by gsmcmullin** [comment]
Support for an embedded JSON parser or Lua interpreter is beyond the scope of this project.
