### ISSUE TITLE
Problem attaching to fully erased STM32F1xx

### ISSUE THREAD

**Issue by gsmcmullin** [blacksphere/blackmagic#5]
Users have reported problems attaching to STM32F1xx with totally erased flash.
The probe stops responding after receiving the vAttach packet.

**Comment by esden** [comment]
Is that still an issue or should we close it? Or are we keeping that open in case someone runs into this issue?

**Comment by esden** [comment]
As we can't reproduce this I am moving this milestone to V1.7

**Comment by esden** [comment]
As this issue was open for very long I am closing this. If this is still an issue for someone please feel free to reopen.
