### ISSUE TITLE
swlink: usbuart_init called unconditionally/twice?

### ISSUE THREAD

**Issue by KillerLink** [blacksphere/blackmagic#506]
I found this by accident, the usbuart_init() is called a) once uncoditionally or  b) twice, which both appears to be not the intended functionality?

https://github.com/blacksphere/blackmagic/blob/e8bd066fe96f72c6998aea7c0d80d6de019b825d/src/platforms/swlink/platform.c#L114-L117

**Comment by gsmcmullin** [comment]
That does look like a mistake.  The conditional one can be removed.

**Comment by KillerLink** [comment]
Issue seems to be resolved by UweBonnes, therefore i close this issue.

**Comment by UweBonnes** [comment]
Forget it, Thanks!
