### ISSUE TITLE
Redundant LDFLAGS entry in make files

### ISSUE THREAD

**Issue by sidprice** [blacksphere/blackmagic#520]
It appears that since BMP was updated to a more recent version of libOpenCM3 the LDFLAGS option to set the MCU stack is no longer required. The linker scripts of locm3 now have the following entry:

`"PROVIDE(_stack = ORIGIN(ram) + LENGTH(ram));" `

This sets the stack to the correct place, at the top of SRAM without the individual platform-specific make files needing to do it.

I don't have all the platforms for testing the changes, but I am happy to make the edits if we can figure out a process for testing.

**Comment by UweBonnes** [comment]
Closed by #525
