### ISSUE TITLE
BUG: Invalid write to stack in pc-hosted jtagtap_tdi_tdo_seq()

### ISSUE THREAD

**Issue by ruabmbua** [blacksphere/blackmagic#542]
jtag_scan defines uint32_t irout, and calls jtagtap_tdi_tdo_seq().
pc-hosted variant casts the pointer argument irout to uint64_t and writes to it.

**How to reproduce:**

Compile PROBE_HOST=pc-hosted with a recent version of GCC (I used 9.2), and
add -fsanitize=address to C_FLAGS and LD_FLAGS.

**Comment by mubes** [comment]
changing target/jtag_scan.c::80 from `uint32_t irout` to `uint64_t irout` fixes the problem and everything works fine.  Basically, its reading in 32 bits of data and the 3 bits of status so that's 35 bits in total. The value is only used as a scratchpad.

**Comment by UweBonnes** [comment]
Fixes with #552
