### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by leogomide** [blacksphere/blackmagic#564]
Greetings, 

Im analysing the bmpm_v2_1c_schematic file, and i see the "PWR_FLAG" icon at the schematic.

Im new to electronics, can somebody tell me why is the VCC pin tied to GND by this label?

Also many thanks for this amazing project :)

![pwrflag](https://user-images.githubusercontent.com/45889239/69973288-079bf280-1502-11ea-812f-8c8eaf4e2fc3.png)

**Comment by sidprice** [comment]
This is a convention with Kicad to indicate a power connection. It is often used when a number of connections of the schematic are defined as "inputs" or "passive" and it may appear to the error checker that the net has no source driving it.

**Comment by leogomide** [comment]
So its just a indicator of a power line, they are not connected to each other, right?

**Comment by sidprice** [comment]
That is correct, they indicate to the error checker that the net has power, but they are not connected to each other.

**Comment by UweBonnes** [comment]
Unrelated to BMP

**Comment by leogomide** [comment]
Thanks for the explanation @sidprice :)
