### ISSUE TITLE
CortexM: Double reset on gdb run command

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#568]
cortexm_reset() first pulse SRST before the target is released, as long as CORTEXM_TOPT_INHIBIT_SRST is not set. Later CORTEXM_AIRCR_VECTKEY | CORTEXM_AIRCR_SYSRESETREQ triggers another reset.

I propose to either remove the reset via srst at all or invert CORTEXM_TOPT_INHIBIT_SRST to CORTEXM_TOPT_ENABLE_SRST so that some device may request this extra reset.

Any opinions?

**Comment by sidprice** [comment]
@UweBonnes , following the discussion about this on Discord suggests that your proposal is a good one. Hopefully the user who was having those issues can comment here.

**Comment by UweBonnes** [comment]
Fixed when #601 gets applied

**Comment by UweBonnes** [comment]
I forgot to close
