### ISSUE TITLE
sam3x: Error erasing flash with vFlashErase packet

### ISSUE THREAD

**Issue by tdaede** [blacksphere/blackmagic#58]
Debugging a SAM3X chip (on the Arduino Due) works in both JTAG and SWD mode, but attempting to load a new elf fails with:

Error erasing flash with vFlashErase packet

This happens in both JTAG and SWD.

**Comment by gsmcmullin** [comment]
It works for me.  Reopen the issue with more information if it's still a problem.

**Comment by Maxattax97** [comment]
I think at this point I've figured out it's the Black Magic and not PlatformIO, because I've tried using [Cortex Debug](https://github.com/Marus/cortex-debug) with the same results (`vFlashErase` error).

I've tried compiling the firmware with the debug flag, which was successful, but when flashed to the BMP with either `dfu-util` or `blackmagic_upgrade`, the LED's flash in the runway pattern, and it's not longer available as a USB device. When I use the daily builds, it acts normally (however the `vFlashErase` error persists), but these daily builds do not have the debug flag enabled, thus I cannot retrieve your requested output.

Tagging @UweBonnes from the other thread.

**Comment by UweBonnes** [comment]
use stm32mem to upgrade

**Comment by Maxattax97** [comment]
I'll need some additional information in order to that. I'm on OpenSUSE which offers `stm32flash` in their repos, are these the same? I ask because OpenSUSE has `dfu-tool` and `dfu-programmer` which _are not_ the same.

```
stm32flash 0.5

http://stm32flash.sourceforge.net/

stm32flash: invalid option -- '-'
Usage: stm32flash [-bvngfhc] [-[rw] filename] [tty_device | i2c_device]
        -a bus_address  Bus address (e.g. for I2C port)
        -b rate         Baud rate (default 57600)
        -m mode         Serial port mode (default 8e1)
        -r filename     Read flash to file (or - stdout)
        -w filename     Write flash from file (or - stdout)
        -C              Compute CRC of flash content
        -u              Disable the flash write-protection
        -j              Enable the flash read-protection
        -k              Disable the flash read-protection
        -o              Erase only
        -e n            Only erase n pages before writing the flash
        -v              Verify writes
        -n count        Retry failed writes up to count times (default 10)
        -g address      Start execution at specified address (0 = flash start)
        -S address[:length]     Specify start address and optionally length for
                                read/write/erase operations
        -F RX_length[:TX_length]  Specify the max length of RX and TX frame
        -s start_page   Flash at specified page (0 = flash start)
        -f              Force binary parser
        -h              Show this help
        -c              Resume the connection (don't send initial INIT)
                        *Baud rate must be kept the same as the first init*
                        This is useful if the reset fails
        -i GPIO_string  GPIO sequence to enter/exit bootloader mode
                        GPIO_string=[entry_seq][:[exit_seq]]
                        sequence=[-]n[,sequence]
        -R              Reset device at exit.

Examples:
        Get device information:
                stm32flash /dev/ttyS0
          or:
                stm32flash /dev/i2c-0

        Write with verify and then start execution:
                stm32flash -w filename -v -g 0x0 /dev/ttyS0

        Read flash to file:
                stm32flash -r filename /dev/ttyS0

        Read 100 bytes of flash from 0x1000 to stdout:
                stm32flash -r - -S 0x1000:100 /dev/ttyS0

        Start execution:
                stm32flash -g 0x0 /dev/ttyS0

        GPIO sequence:
        - entry sequence: GPIO_3=low, GPIO_2=low, GPIO_2=high
        - exit sequence: GPIO_3=high, GPIO_2=low, GPIO_2=high
                stm32flash -R -i -3,-2,2:3,-2,2 /dev/ttyS0
```

I trust this is safe to do even though we're working with SAM3X? Also a miniature tutorial would be helpful... I really don't want to wipe out my bootloader.

**Comment by UweBonnes** [comment]
Use " scripts/stm32_mem.py src/blackmagic.bin" to update. It verifys the flash written and so you can try to use the upper 64 k Flash on s STM32F103x8.

Stm32Flash is for using the builtin serial bootloader

**Comment by UweBonnes** [comment]
Please review my additions to the FAQ.

**Comment by Jimbles** [comment]
Hi there, I am having a similar problem trying to get the debugger working with an Arduino Due (I was directed here from the Platformio forums). I am very new to all this (as in, im not even quite sure how to invoke gdb from the command line), and unfortunately I am stuck using Windows10 for now, so can I please double check the procedure? 

I have a BMP S/N 2056, so I guess that has v1.6.1 firmware on it, so I need to upgrade to the latest daily build? And for this i need to install df-util and zadig. With this latest firmware debugging should just work on the Arduino Due through platformio? Thanks!

**Comment by UweBonnes** [comment]
Hijacking some nearly unrelated issue is no good. Head over to the blackmagic gitter channel. Check also the wiki so less redunbdant questions get asked.

**Comment by Jimbles** [comment]
Im sorry, I thought this was a related issue because it is the solution to the problem I am having (Arduino Due debugging) and the additions the FAQ you added on the issue were the steps I was going to take to solve it. Didnt intend to hijack the issue
