### ISSUE TITLE
EFR32 support

### ISSUE THREAD

**Issue by denigmus** [blacksphere/blackmagic#590]
Any plan to support EFR32 for at least batch programming? I see EFM32 is already supported.

**Comment by UweBonnes** [comment]
BMP is a community effort. Device support is added via Pull Requests from owner of the hardware who implement and test the support.

**Comment by kanflo** [comment]
Just out of curiosity, what does "batch programming" refer to? General EFR32 support is on master, flashing included.

**Comment by denigmus** [comment]
Batch programming described here 
https://github.com/blacksphere/blackmagic/wiki/GDB-Automation

**Comment by UweBonnes** [comment]
You can also use PC-hosted BMP platforms like "blackmagic_stlinkv2 bla.bin" to flash at 0x08000000 or with otional modifiers. But also gdb batch programming should work.

**Comment by kanflo** [comment]
Does "regular programming" work for your device (ie. nor in batch mode) or is the chip completely unsupported (ie. not found when probing)?

**Comment by denigmus** [comment]
I don't have this debugger at all and know nothing about it. :) I just 
review options for a batch programming of EFR32.

**Comment by kanflo** [comment]
It will most likely work fine unless the firmware quickly enters EM4 as the BMP currently lacks support for the "AAP Expansion Sequence". I say "most likely" as the EFM/EFR:s I have encountered so far work fine but as always, YMMV.

**Comment by UweBonnes** [comment]
Just stumble on this:
> grep -i -r efr32 target/efm32.c 
 * EFM32, EZR32 and EFR32 devices are all currently supported through
 * * EFR32BG13P532F512GM32 (EFR Blue Gecko)
        {16, "EFR32MG1P", 2048, 0x400e0000, true, 2048, 10240, "Mighty Gecko"},
        {17, "EFR32MG1B", 2048, 0x400e0000, true, 2048, 10240, "Mighty Gecko"},
        {18, "EFR32MG1V", 2048, 0x400e0000, true, 2048, 10240, "Mighty Gecko"},
        {19, "EFR32BG1P", 2048, 0x400e0000, true, 2048, 10240, "Blue Gecko"},
        {20, "EFR32BG1B", 2048, 0x400e0000, true, 2048, 10240, "Blue Gecko"},
        {21, "EFR32BG1V", 2048, 0x400e0000, true, 2048, 10240, "Blue Gecko"},
        {25, "EFR32FG1P", 2048, 0x400e0000, true, 2048, 10240, "Flex Gecko"},
        {26, "EFR32FG1B", 2048, 0x400e0000, true, 2048, 10240, "Flex Gecko"},
        {27, "EFR32FG1V", 2048, 0x400e0000, true, 2048, 10240, "Flex Gecko"},
        {28, "EFR32MG12P", 2048, 0x400e0000, true, 2048, 32768, "Mighty Gecko"},
        {29, "EFR32MG12B", 2048, 0x400e0000, true, 2048, 32768, "Mighty Gecko"},
        {30, "EFR32MG12V", 2048, 0x400e0000, true, 2048, 32768, "Mighty Gecko"},
        {31, "EFR32BG12P", 2048, 0x400e0000, true, 2048, 32768, "Blue Gecko"},
        {32, "EFR32BG12B", 2048, 0x400e0000, true, 2048, 32768, "Blue Gecko"},
        {33, "EFR32BG12V", 2048, 0x400e0000, true, 2048, 32768, "Blue Gecko"},
        {37, "EFR32FG12P", 2048, 0x400e0000, true, 2048, 32768, "Flex Gecko"},
        {38, "EFR32FG12B", 2048, 0x400e0000, true, 2048, 32768, "Flex Gecko"},
        {39, "EFR32FG12V", 2048, 0x400e0000, true, 2048, 32768, "Flex Gecko"},
        {40, "EFR32MG13P", 2048, 0x400e0000, true, 2048, 16384, "Mighty Gecko"},
        {41, "EFR32MG13B", 2048, 0x400e0000, true, 2048, 16384, "Mighty Gecko"},
        {42, "EFR32MG13V", 2048, 0x400e0000, true, 2048, 16384, "Mighty Gecko"},
        {43, "EFR32BG13P", 2048, 0x400e0000, true, 2048, 16384, "Blue Gecko"},
        {44, "EFR32BG13B", 2048, 0x400e0000, true, 2048, 16384, "Blue Gecko"},
        {45, "EFR32BG13V", 2048, 0x400e0000, true, 2048, 16384, "Blue Gecko"},
        {49, "EFR32FG13P", 2048, 0x400e0000, true, 2048, 16384, "Flex Gecko"},
        {50, "EFR32FG13B", 2048, 0x400e0000, true, 2048, 16384, "Flex Gecko"},
        {51, "EFR32FG13V", 2048, 0x400e0000, true, 2048, 16384, "Flex Gecko"},
        {52, "EFR32MG14P", 2048, 0x400e0000, true, 2048, 16384, "Mighty Gecko"},
        {53, "EFR32MG14B", 2048, 0x400e0000, true, 2048, 16384, "Mighty Gecko"},
        {54, "EFR32MG14V", 2048, 0x400e0000, true, 2048, 16384, "Mighty Gecko"},
        {55, "EFR32BG14P", 2048, 0x400e0000, true, 2048, 16384, "Blue Gecko"},
        {56, "EFR32BG14B", 2048, 0x400e0000, true, 2048, 16384, "Blue Gecko"},
        {57, "EFR32BG14V", 2048, 0x400e0000, true, 2048, 16384, "Blue Gecko"},
        {61, "EFR32FG14P", 2048, 0x400e0000, true, 2048, 16384, "Flex Gecko"},
        {62, "EFR32FG14B", 2048, 0x400e0000, true, 2048, 16384, "Flex Gecko"},
        {63, "EFR32FG14V", 2048, 0x400e0000, true, 2048, 16384, "Flex Gecko"},

**Comment by UweBonnes** [comment]
Closing as no feedback . EFR should be supported and batch programming can be done with PC-hosted variants
