### ISSUE TITLE
Firmware upgrade successful but no cdc_acm

### ISSUE THREAD

**Issue by passion-creativity-enthusiasm** [blacksphere/blackmagic#61]
Dear all,

I recently got my hands on BMP. I followed the instructions found here:

1) https://pixhawk.org/dev/jtag/black_magic_probe

I was able to get "All Operations Successful". However, when I did "dmesg", I wasn't able to see cdc_acm ttyACM0 and ttyACM1.

I suspect I am having the exact same problem as issue #43 - Black Magic Mini firmware update failed. I am having a green LED turning on once powered but nothing else.

Would be great to hear from developers on how I could get the cdc_acm ttyACM0 and ttyACM1 up again!

Many thanks,
Kenny

**Comment by gsmcmullin** [comment]
Followed up privately.
