### ISSUE TITLE
swlink: strange behavior on macos

### ISSUE THREAD

**Issue by skotopes** [blacksphere/blackmagic#624]
Basically you can perform only one debug session. After you disconnect, bmp doesn't talk to gdb anymore.

Looks like there is a some kind of condition race with handling control requests on cdcacm side that leaves bmp in wrong state. So debugging show that bmp is trying to send data over closed serial port with cdcacm_gdb_dtr=0.

**Comment by esden** [comment]
@skotopes Any progress on debugging this? Is it still an issue with the most recent firmware?

**Comment by skotopes** [comment]
@esden no progress last I've checked.

I've abandoned ideas on fixing it, instead we've ported BM to esp-s2 and solved issue there(https://github.com/flipperdevices/blackmagic-esp32-s2). We use totally different stack and FreeRTOS, so no back port possible.

**Comment by esden** [comment]
Ok, thank you! :) I am closing the issue then.
