### ISSUE TITLE
Racist project name

### ISSUE THREAD

**Issue by BlackLivesMatterPower** [blacksphere/blackmagic#680]
I have a general issue with the debugger being called "blackmagic".
Regardless of the author's intent, "black magic" is a term that traditionally refers to supernatural or magic powers being used for evil.
This use of this name therefore propagates the sentiment that there is something inherently evil about the color black, and I think this name should be substituted to avoid racial connotations.

**Comment by spam-receiver** [comment]
"Black magic", because with it you can program microcontrollers for free. This is a type of "witchcraft." And not because someone is black or white there.

**Comment by UweBonnes** [comment]
Not a technical issue.
