### ISSUE TITLE
arm-cortexm3-eabi-gcc: Command not found

### ISSUE THREAD

**Issue by phillowcompiler** [blacksphere/blackmagic#685]
I tried to build the firmware as
`make CROSS_COMPILE=arm-cortexm3-eabi-`

But cannot...

```
 GIT include/version.h
  CC      target/adiv5.c
make[1]: arm-cortexm3-eabi-gcc: Command not found
Makefile:95: recipe for target 'adiv5.o' failed
make[1]: *** [adiv5.o] Error 127
Makefile:23: recipe for target 'all' failed
make: *** [all] Error 2

```
Please tell me what is "arm-cortexm3-eabi-gcc" command...

my gcc-arm-none-eabi is 15:6.3.1+svn253039-1+10.

**Comment by UweBonnes** [comment]
Where did you get that strange "CROSS_COMPILE=arm-cortexm3-eabi-" information from? I do not find in the repo or wiki.
If the "arm-none-eabi-" toolchain is available on your system, "make" is enough to build for BMP native.

**Comment by phillowcompiler** [comment]
Thank you!

I follow this.
https://github.com/blacksphere/blackmagic/wiki/Hacking

Yes, only
`make`
is done!

Thank you
