### ISSUE TITLE
Hardware unreachable after dfu update

### ISSUE THREAD

**Issue by llllVIIII** [blacksphere/blackmagic#686]
Hi it seems I updated the blackmagic probe with the wrong fw bin file via dfu_util. Now I am unable to update it any more. Is it possible to flash it via a Jlink?

This is how I flashed it:

```
 ➜  blackmagic git:(master) sudo dfu-util -d 1d50:6018,:6017 -s 0x08002000:leave -D src/blackmagic_dfu.bin
 Password:
 dfu-util 0.9
 
 Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
 Copyright 2010-2016 Tormod Volden and Stefan Schmidt
 This program is Free Software and has ABSOLUTELY NO WARRANTY
 Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
 
 dfu-util: Invalid DFU suffix signature
 dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
 Opening DFU capable USB device...
 ID 1d50:6018
 Run-time device DFU version 011a
 Claiming USB DFU Runtime Interface...
 Determining device status: state = appIDLE, status = 0
 Device really in Runtime Mode, send DFU detach request...
 Device will detach and reattach...
 Opening DFU USB Device...
 Claiming USB DFU Interface...
 Setting Alternate Setting #0 ...
 Determining device status: state = dfuIDLE, status = 0
 dfuIDLE, continuing
 DFU mode device DFU version 011a
 Device returned transfer size 1024
 DfuSe interface name: "Internal Flash   "
 Downloading to address = 0x08002000, size = 7104
 Download    [=========================] 100%         7104 bytes
 Download done.
 File downloaded successfully
 Transitioning to dfuMANIFEST state
```

I guess this was the wrong address offset?

**Comment by UweBonnes** [comment]
Replug and press the "force bootloader entry" buttom. Then dfu transfer the right image. Report success or post output when problems happen.

**Comment by llllVIIII** [comment]
So do I understand it correct that I have to flash it with offset of 0x8000000 and not 0x8002000?

**Comment by UweBonnes** [comment]
"dfu-util -l" show the area reachable by dfu. BMP firmware loads to 0x08002000 or in the case you compiled for stlink  with "make PROBE_HOST=stlinl ST_BOOTLOADER=1" at 0x08004000 to allow to upload with stlink-tool to an stlinkv2 with original ST-stlinkv2 bootloader.

**Comment by llllVIIII** [comment]
Okay, I have the original black magic Probe and compiled it via "make" I have the arm-none-eabi tool chain in my path.

**Comment by llllVIIII** [comment]
So I successfully flashed the new FW on my BMP. I would suggest to update the Wiki:

https://github.com/blacksphere/blackmagic/wiki/Upgrading-Firmware

Here is says you should flash the blackmagic-native.bin. But the makefile does not generate suche a file but a plain blackmagic.bin file. Also more up to date information was found here:

https://github.com/blacksphere/blackmagic/wiki/Hacking

**Comment by UweBonnes** [comment]
Please read Upgrading-Firmware again!

**Comment by llllVIIII** [comment]
Well, you are absolutely right. I should have read it more carefully. Thanks anyway for the quick replay and your patience 😊
