### ISSUE TITLE
Newbie question. How to read/write at particular address ?

### ISSUE THREAD

**Issue by luqasz** [blacksphere/blackmagic#716]
Hi.

For now I am using st-link with `st-flash` command to read/write flash/EEPROM. How to do the same with BMP ?

**Comment by UweBonnes** [comment]
Compile BMP-hosted and run "blackmagic <file.bin>

**Comment by luqasz** [comment]
Thx. And how to read current eeprom/flash content from target ?

**Comment by UweBonnes** [comment]
Get help with "blackmagic -h" and look for the "-r" option.

**Comment by luqasz** [comment]
Thx. So it's only available with hosted version ?

**Comment by UweBonnes** [comment]
There is python script to do so in a limited range in the script directory. What is the problem with hosted?

**Comment by luqasz** [comment]
I am wondering if I will flash my f3 discovery board with BMP, will I loose ability to read/write at particular address.

**Comment by UweBonnes** [comment]
Your last posting is totally unclear!

**Comment by luqasz** [comment]
I have a F3 discovery board with stlink embedded. My concern with BMP (replacing stlink) is:
* will I be able to write to a given memory address (EEPROM, FLASH)
* will I be able to read from given address (EEPROM, FLASH)

Is it more clear now ?

**Comment by UweBonnes** [comment]
Run BMP-Hosted with the recent original ST Link firmware. Then you have choice to use ST software, st-link,pyocd and BMP. An BMP allow all of the above with hosted and the right arguments. BMP firmware only writes ELF files, so to write to a given address you need a fitting elf or hex file.

**Comment by luqasz** [comment]
Ok, Thx for explanation.
