### ISSUE TITLE
BMP Native fails with "mon s" on some devices

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#723]
SWD timing on BMP-Native with firmware as distributed with the dongle (at least August 20) have very short high times. Some devices, e.g. the very low power Micro Apollo3 work unreliable with this small pulses. Wiring influence may worsen the situtation.

If you happen to have those problems, update to recent software.

**Comment by esden** [comment]
The current BMP-Native hardware ships with firmware V1.7.1. Is that still an issue with the new firmware? If not, then we should close the issue. Issues are not meant as documentation, if this needs to be communicated to users it should go into the Wiki FAQ section. I am closing this for now.
