### ISSUE TITLE
usb icdi error windows 10

### ISSUE THREAD

**Issue by daguirrem** [blacksphere/blackmagic#740]
![image](https://user-images.githubusercontent.com/49079545/94641245-56dbbc80-02a6-11eb-8fd1-a60a91ea2701.png)
The launchpad-icdi version appears as unknown device on device manager on windows 10 with the latest version of firmware, i have a older version (i don't know exactly which one) that works well

**Comment by UweBonnes** [comment]
Is the the same PC setup as with the succeeding tests earlier? Is the blackmagic.inf file installed? Does the icdi  work on a linux box?

**Comment by daguirrem** [comment]
Yes, i test the 2 firmwares at same time (and on same pc) and the older works fine, i think that can't probe on a VM becouse Windows alerts me like when we connect a damage usb, directly can't update (or do something) with the driver and the device.

### The older version that works (with the number of firmware):
![image](https://user-images.githubusercontent.com/49079545/94694221-3a696f80-02fa-11eb-919f-57ee99282697.png)

### The new version (unknow device) (with windows event report) :
![image](https://user-images.githubusercontent.com/49079545/94694818-dabf9400-02fa-11eb-8e10-2b985ec15b2f.png)
![image](https://user-images.githubusercontent.com/49079545/94695084-1ce8d580-02fb-11eb-96a2-5f1a1b81f90d.png)
![image](https://user-images.githubusercontent.com/49079545/94695109-22462000-02fb-11eb-99b5-2e78a99d5d1d.png)

**Comment by UweBonnes** [comment]
As asked above, check that driver/blackmagic.inf is installed

**Comment by daguirrem** [comment]
is the .inf necesary for windows 10? when i try install appears error: "Third-party INF does not contain digital signature information" and the wiki just specify the driver for windows 7 and older

**Comment by UweBonnes** [comment]
Probably not, but I do not work on windows. Compiles some old firmware, load it and check if that works. If you are sure it is an error with the firmware, do a bisect.

**Comment by esden** [comment]
As the icdi usb error patch is merged now I assume this issue is resolved? Closing.
