### ISSUE TITLE
LPC21xx support

### ISSUE THREAD

**Issue by maknoll** [blacksphere/blackmagic#76]
I would like to write support for the LPC21xx ARM7TDMI family. Maybe you could give me some hints what has to be implemented?

**Comment by gsmcmullin** [comment]
Hi Martin

To start, the support for the ARM7TDMI support will need to be finished.
There is an unfinished driver here:
https://github.com/blacksphere/blackmagic/blob/master/src/arm7tdmi.c

I'm no longer working with any ARM7 devices, so have had little motivation
to finish this.
At the very least the functions to read and write memory need to be
implemented.  The function pointers need to be filled in the target
structure in arm7tdmi_jtag_handler().
You'll need to check the ARM literature for how to implement these
functions.

Once the core functions are all implemented, an LPC21xx driver will need to
be written that provides the XML memory map to GDB and implements flash
programming routines.

Cheers,
Gareth


On Thu, Jan 29, 2015 at 4:11 AM, Martin Knoll <notifications@github.com>
wrote:

> I would like to write support for the LPC21xx ARM7TDMI family. Maybe you
> could give me some hints what has to be implemented?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/blacksphere/blackmagic/issues/76>.
>



-- 
*Black Sphere Technologies Ltd.*

Web: www.blacksphere.co.nz
Mobile: +64 27 777 2182
Tel: +64 9 478 8885
Skype: gareth.mcmullin
LinkedIn: http://nz.linkedin.com/in/gsmcmullin

**Comment by maknoll** [comment]
Thanks for your support. Since i don't know if and when i will finish this endeavor and it is not a real issue i'm closing it.
