### ISSUE TITLE
What are the max speed and specs of the USB to UART feature of BMP?

### ISSUE THREAD

**Issue by pvonmoradi** [blacksphere/blackmagic#761]
I've flashed the BMP firmware on a STM32F103. I couldn't find any specs on the bonus built-in USB<->UART feature. Are the specs similar to the UART peripheral specs of the board or are they further limited by BMP firmware?  
![screenshot-2020-10-22-01:07:58](https://user-images.githubusercontent.com/1058151/96790075-11249680-1403-11eb-85cc-dbf95ee66707.png)

**Comment by UweBonnes** [comment]
Yes. But not sustained!
