### ISSUE TITLE
success make but fail make probe_host=var

### ISSUE THREAD

**Issue by stkenneth** [blacksphere/blackmagic#778]
Hi, i have success building this project when I do "make", but always fail when I do "make PROBE_HOST=swlink" tried change it to hosted,stlink and fail. but without the PROBE_HOST comment, always success.

I am on windows 10 using minGW and Msys trying to build bmp for a blue pill.

**Comment by UweBonnes** [comment]
Did you resolve the problem? Otherwise post relevant output

**Comment by stkenneth** [comment]
> Did you resolve the problem? Otherwise post relevant output

yes i think i just did, but still need to test if it is successful.

what i did is make clean && make PROBE_HOST=swlink, and now it returns no error. but will test and report in a while.

**Comment by StonedDawg** [comment]
ok, so `make clean && make PROBE_HOST=swlink` solved the problem
