### ISSUE TITLE
what is the role for PWR_FLAG in schematic 

### ISSUE THREAD

**Issue by mttbx** [blacksphere/blackmagic#789]
I don't know why PWR_FLAG is connected to the GND, this will shutdown the power of the target. And I find that the two p mos 
 in DMG1023UV-7 is always close because the voltage of the gate is always bigger equal then the voltage of the source. Should it be DMG1024UV-7? Can you help me?

**Comment by UweBonnes** [comment]
I try to contact Esden about that. It it his design that he warped from Garteths design

**Comment by sidprice** [comment]
The "Power Flag" in Kicad tells the electrical rules checker that the net it is attached to is a power net.

**Comment by mttbx** [comment]
Thank you! Waiting for the answer to the second question.

**Comment by esden** [comment]
The DMG1023UV-7 is a true switch Mosfet circuit. When it is off it prevents the target from being powered as well as the probe being powered by the target. Google for true switch circuits. For example: https://www.homemade-circuits.com/bidirectional-switch/ You can build it with N-MOSFET and P-MOSFET but I found that the P-MOSFET version worked better.

**Comment by mttbx** [comment]
Thank you for your guidance!
