### ISSUE TITLE
Is it possible to support riscv arch?

### ISSUE THREAD

**Issue by mttbx** [blacksphere/blackmagic#794]
Gdb and jtag facility can be reused. And I find that the quality of the code in this project is very high. I think this project have the potential to support more arch.

**Comment by UweBonnes** [comment]
Look at the PRs. Several approaches have been tried.

**Comment by UweBonnes** [comment]
https://github.com/UweBonnes/blackmagic/tree/ruabmbua gets some way through the debug setup.

**Comment by mttbx** [comment]
Thank you for your help!

**Comment by mttbx** [comment]
It seems there's some works need to be done for rvdbg-013.

**Comment by mttbx** [comment]
Hoping rbdbg-013 will be supported soon!
