### ISSUE TITLE
libftdi1 not found

### ISSUE THREAD

**Issue by chriskuku** [blacksphere/blackmagic#823]
WHen trying to compile blackmagic with PROBE_HOST=hosted Im getting:

$ make PROBE_HOST=hosted
 GIT include/version.h
Package libftdi1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libftdi1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libftdi1' found
Package hidapi-libusb was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-libusb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hidapi-libusb' found

**Comment by chriskuku** [comment]
Forgot to mention that my host is macOS (Catalina 10.15.7). I'm trying to install the required packages through macports right now and see how it works out.

**Comment by eclig** [comment]
You need something like "sudo apt install libftdi1-dev" or whatever it's
spelled ob a Mac.

chriskuku <notifications@github.com> schrieb am Sa., 26. Dez. 2020, 10:28:

**Comment by chriskuku** [comment]
I solved it after some weird rounds through port install. I got libftdi1 installed in /opt/local and included 
-I/opt/local/include in the Makefile and still got an undefined 
```

Package hidapi-libusb was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-libusb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hidapi-libusb' found
```


until I found that all resolves so to say "blackmagically" when you supply the following arguments to your make command line:

`make PROBE_HOST=hosted HOSTED_BMP_ONLY=1`

With that all the 'hidapi-libusb' and libftdi1 stuff will not be required.

**Comment by UweBonnes** [comment]
HOSTED_BMP_ONLY=1 on MACOS is not really what you want, as remote protocoll on MACOS needs some love. Normal "hosted" offers the BMP gdb server and command line for other debugers.

**Comment by UweBonnes** [comment]
Seems resolved
