### ISSUE TITLE
Is it possible to debug arm9 with cortexa?

### ISSUE THREAD

**Issue by mttbx** [blacksphere/blackmagic#844]
Is it possible? Or needs some modifications? Because arm9 is also a 32 bits arm core.

**Comment by mttbx** [comment]
And is it possible to debug cortex-a7?

**Comment by UweBonnes** [comment]
Garteth did some work on Cortex-A. Dig in the git history and in his repo.

**Comment by mttbx** [comment]
Thank you

**Comment by mttbx** [comment]
I can't find his repo. Maybe he delete it.
