### ISSUE TITLE
Wiki graphics does not mention recent added families

### ISSUE THREAD

**Issue by UweBonnes** [blacksphere/blackmagic#850]
https://raw.githubusercontent.com/wiki/blacksphere/blackmagic/images/bmpm_ARM_Cortex-_targets.png should mention:
- STM32H7
- STM32G0/4
- STM32L5
- LPC546
-  Kinetis KE04

**Comment by UweBonnes** [comment]
- Raspberry RP2040 pending as PR

**Comment by esden** [comment]
Ok,

I have added the parts you listed. Except RP2040. When that is in, please open a new issue and assign it to me. I will add it.

https://raw.githubusercontent.com/wiki/blacksphere/blackmagic/images/bmpm_ARM_Cortex-M_targets-2021.png

Cheers,
Piotr

**Comment by esden** [comment]
The updated list is now uploaded. When new chips need to be added to the documentation please open new issues and assign them to me. Thank you.
