### ISSUE TITLE
Implicit function declaration

### ISSUE THREAD

**Issue by JDuchniewicz** [blacksphere/blackmagic#889]
I am trying to build bmp with target `PROBE_HOSH=swlink` and I am getting these errors:

```
target/efm32.c: In function ‘efm32_probe’:
target/efm32.c:645:2: error: implicit declaration of function ‘sniprintf’ [-Werror=implicit-function-declaration]
  snprintf(priv_storage->efm32_variant_string,
  ^
target/efm32.c: In function ‘efm32_aap_probe’:
target/efm32.c:1018:2: error: implicit declaration of function ‘siprintf’ [-Werror=implicit-function-declaration]
  sprintf(priv_storage->aap_driver_string,
  ^
cc1: all warnings being treated as errors
make[1]: *** [Makefile:99: efm32.o] Error 1
make: *** [Makefile:17: all] Error 2
```

I installed `arm-none-eabi-{gcc, newlib}`.

**Comment by UweBonnes** [comment]
Check your installation of newlib/nanolib! Who does provide newlib on your system? I use https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by JDuchniewicz** [comment]
I installed a package from AUR (Arch Linux, usually it should just work). Maybe the newlib differs (is newer probably) from the ones tested usually on.

**Comment by UweBonnes** [comment]
Try to compile with the whole block of sniprintf and friends defines removed. For me, a test resulted in a binary  20 byte larger.

**Comment by esden** [comment]
@JDuchniewicz were you able to compile the firmware? If not I can check how my setup looks like on arch and update the documentation.

**Comment by JDuchniewicz** [comment]
I settled for the pre-built binary if I correctly remember.

**Comment by esden** [comment]
Ok, that sounds good. I will close this issue then. :)

**Comment by JDuchniewicz** [comment]
Hopefully it won't bite back in the future (maybe it was just due to toolchain misconfiguration or exotic hardware setup 🤷🏽)
