### ISSUE TITLE
Semihosting call SYS_EXIT is implemented incorrectly

### ISSUE THREAD

**Issue by pavel-kirienko** [blacksphere/blackmagic#943]
"Semihosting for AArch32 and AArch64" says:

> On entry, the PARAMETER register is set to a reason code describing the cause of the trap.

This appears to mean that the probe is expected to collect the reason code directly from `r1`, which is unlike most other semihosting calls. In the current implementation, the reason code is read through indirection based on the memory address contained in `r1`. The culprit is here:

https://github.com/blacksphere/blackmagic/blob/e1a928beb1210d10e862a6eb782e8836337b9665/src/target/cortexm.c#L1217

For comparison, this system call seems to be implemented correctly in OpenOCD:

https://github.com/openocd-org/openocd/blob/53556fcded056aa62ffdc6bf0c97bff87d891dab/src/target/semihosting_common.c#L352

Also, the standard reason codes such as `ADP_Stopped_ApplicationExit` are not checked.

**Comment by koendv** [comment]
OK. IIUC,  you suggest changing the 32-bit SYS_EXIT as:
```
--- a/src/target/cortexm.c
+++ b/src/target/cortexm.c
@@ -1605,7 +1605,7 @@ static int cortexm_hostio_request(target *t)
 #endif
 
        case SYS_EXIT: /* _exit() */
-               tc_printf(t, "_exit(0x%x)\n", params[0]);
+               tc_printf(t, "_exit(0x%x)\n", arm_regs[0]);
                target_halt_resume(t, 1);
                break;

```
and perhaps also as:
```
--- a/src/target/cortexm.c
+++ b/src/target/cortexm.c
@@ -1214,8 +1214,8 @@ static int cortexm_hostio_request(target *t)
 
        t->tc->interrupted = false;
        target_regs_read(t, arm_regs);
-       target_mem_read(t, params, arm_regs[1], sizeof(params));
        uint32_t syscall = arm_regs[0];
+       if(syscall != SYS_EXIT) target_mem_read(t, params, arm_regs[1], sizeof(params));
        int32_t ret = 0;
 
        DEBUG_INFO("syscall 0"PRIx32"%"PRIx32" (%"PRIx32" %"PRIx32" %"PRIx32" %"PRIx32")\n",

```
Is this correct?

> Also, the standard reason codes such as `ADP_Stopped_ApplicationExit` are not checked.

The exit codes are printed in a terse way to save a few bytes.

**Comment by pavel-kirienko** [comment]
>Is this correct?

Yes.

>The exit codes are printed in a terse way to save a few bytes. This could be changed.

I also have a question related to SYS_EXIT but not necessarily related to this project, if you could help that would be appreciated. When I run my application via GDB on the target in batch mode with `-return-child-result`, calling SYS_EXIT makes the GDB process exit with status code 255 regardless of the argument passed via the system call (I know the actual value received by the debugger because it is printed as you mentioned).

I would like the exit code passed to SYS_EXIT to be translated to the GDB process because I am using this setup to run unit tests on my hardware, and the exit code should, ideally, indicate whether the test suite was executed successfully or not. Is there a solution to this other than switching to OpenOCD?

**Comment by koendv** [comment]
OK. IIUC, you wish to use the exit code in an automated process.
This is a tentative solution:

- if you run bmp hosted - on the pc - then when sys_exit() is called the "blackmagic" process exits. The exit code depends upon the value passed to sys_exit():
If the value is ADP_STOPPED_APPLICATION_EXIT (0x20026) the exit code is 0.
If the value is ADP_STOPPED_RUNTIME_ERROR (0x20023) the exit code is 1.
In all other cases, the exit code is the value passed to sys_exit()
This is more or less the way openocd does it.

- If you run bmp in e.g. a bluepill/stlink, the exit value is printed in hex, and the program goes in breakpoint.

[sysexit_patch.txt](https://github.com/blacksphere/blackmagic/files/7466457/sysexit_patch.txt)

Opinion?

Another way - completely unrelated - is using semihosting to write test results to file, and use diff to compare test output with the correct results. The exit code of diff can then be used.

**Comment by pavel-kirienko** [comment]
The patch looks good.

I run black magic on a hardware probe, and I already have a workaround in place that reads the number of failed tests from a file that is written by the target via semihosting (similar to what you suggested). This workaround is okay for now but eventually, I would like to implement the proper solution, hence why I was inquiring about this. Is it in principle possible to communicate a specific exit status to the GDB client?

**Comment by koendv** [comment]
I think that to implement that one has to touch code that is best
left alone. 

koen

**Comment by esden** [comment]
Considering that the semihosting patch #944 is merged I consider this issue as resolved. If that is not the case please feel free to reopen this issue. :)
