### ISSUE TITLE
How to Change SSID & PASSWORD of blackmagic?

### ISSUE THREAD

**Issue by Kothiyaparth** [blacksphere/blackmagic#961]
I want to change default SSID name and password how can I do this and how to rebuild it?

**Comment by DX-MON** [comment]
If you're taking about the Blackmagic Design cards, and one which has WiFi then you have come to the wrong repo.
This repo is for the BlackMagic Probe JTAG-based debugger which has no affiliation with Blackmagic Design.

**Comment by UweBonnes** [comment]
There are also some WIFI enabled debuggers, based on BMP, but with a different codebase. Get in contact with those projects.

**Comment by esden** [comment]
@Kothiyaparth if you are referring to [ctxLink](https://www.crowdsupply.com/sid-price/ctxlink), you will have to ask @sidprice, he maintains his probes [firmware separately](https://github.com/sidprice/blackmagic/tree/ctxLink_master) and you will have to contact him. Or if you are talking about [other an ESP32](https://github.com/Ebiroll/esp32_blackmagic) you should also contact those specific projects.

In any case. As this does not seem to be related to the official firmware that we are maintaining here I will close this issue. If we made a mistake here, please feel free to comment and/or reopen this issue. :)
